### ISSUE TITLE
Menu takes a sec to load

### ISSUE THREAD

**Issue by card100** [Nanomotion/Nano-IDE#2]
![ice_video_20170324-173434](https://cloud.githubusercontent.com/assets/17168923/24319323/900bd324-10e6-11e7-9b1b-7b8440f85ea0.gif)

**Comment by card100** [comment]
Well, it doesn't show it there... But it's noticeable on my little laptop.

**Comment by zspri** [comment]
How long does it take for the menu to open?

**Comment by card100** [comment]
Just 1 sec but it loads in separate parts.

**Comment by card100** [comment]
I don't know how much you can do about it.

**Comment by zspri** [comment]
I can't really do anything about it, sorry. It's an issue with Visual Basic's rendering.
